### ISSUE TITLE
End-to-end receive ETH flow

### ISSUE THREAD

**Issue by mhluongo** [tallycash/extension#103]
- [x] New wallet creation / onboarding frontend integrated with the backend (#242)
  - [x] New key material is created (#237)
  - [x] New key material is persisted (#237)
- [x] Frontend should pull persisted accounts at startup
- [x] Frontend pulls account balances from the backend
  - [x] At startup
  - [x] and live
- [x] Backend should have updated account balances
  - [x]  Periodically
  - [x]  and live
- [x] #104
- [ ] Notifications for receiving ETH
  - [x] #105
  - [ ] #106
- [x] Transaction history is updated with receipt
  - [x] Simple case of receiving ETH
  - [x] More complex case as a contract interaction side-effect
