### ISSUE TITLE
End-to-end send ETH flow

### ISSUE THREAD

**Issue by mhluongo** [tallycash/extension#131]
- [x] Key import interface (#237)
- [x] Transaction signature API (#248)
- [x] Transaction signature backend (#158)
- [ ] Confirm the UI shows transaction confirmations (#233)
- [ ] Wire up the signature page (#231)
- [ ] EIP-1559 gas selection design (#229)
- [x] #294
- [ ] Request tx signature from backend (#231)
- [ ] Broadcast transaction to network (#258)
- [x] Kick off account tracking when a new key is added (#241)
- [x] Recovery phrase UI hookup (#242)
