### ISSUE TITLE
Performance improvements

### ISSUE THREAD

**Issue by mr-michael** [tallycash/extension#1350]
# Acceptance criteria
We don't see significant spikes in cpu usage when 8-10 addresses are tracked.

# Work breakdown
- [ ] #1885 
- [ ] “block” and “accountWithBalance” event ddos
- [ ] assets - initialize on app start and don't persis
- [ ] finish #1296 to make persisting state reasonable
- [ ] try patching BigInt so we don't have to check every property if it's bigint [here](https://github.com/tallycash/extension/blob/831676b8807e61b59a99821f0cc2ba80992b8f3f/background/lib/utils/index.ts#L77)  but use only a simple `JSON.stringify()` (ugly hack, only worth it if the performance gain is significant)
- [x] #1563
  - Set up scripted stress/load testing if necessary/unsure
- [x] prune unused data from redux and/or implement paging [flowdock thread](https://www.flowdock.com/app/cardforcoin/tech/threads/mBOx5TsYPZ6JNqtUg0dJ42cRiJg) (activities, logs, transaction inputs)
- [x] #1838 
- [x] #1837  
- [x] #1376 
- [x] #1363 
- [x] #1296 
- [x] #1722  
- asset list size decrease?
- nft reload issue > why does it reload periodically? 
- prices batch persist into indexedDB
- check if there is a better way to generate the cachekey for `memoizedMergeAssets`
  
# Ideas
- [Performance Improvements RFC](https://coda.io/d/Minimum-Viable-Launch_dznBnP8Wtkc/RFC-Performance-improvements_subOr#_lu1RQ)

**Comment by greg-nagy** [comment]
- [ ] Optimize main startup time
  - move store initialization into the `create()` function https://github.com/tallycash/extension/pull/1672#issuecomment-1167641973
    - move all redux stuff into a separate file
    - maybe `redux-slices/index` too

**Comment by greg-nagy** [comment]
https://github.com/tallycash/extension/issues/1564#issuecomment-1183573986

There's a performance issue is mentioned here: https://github.com/tallycash/extension/issues/1742#issuecomment-1176375994

And discussion in [flowdock](https://www.flowdock.com/app/cardforcoin/tech/threads/tZtrk7Ye89GhvY51NDoXJfpMBUo)

From a cursory look, `getCachedAssets` is merging assets I think twice per call. And `getCachedAssets` is running hundreds of times in unison, particularity noticeable at startup or when adding an address

**Comment by greg-nagy** [comment]
https://github.com/tallycash/extension/issues/1564#issuecomment-1195545200

Just a quick notes from my personal list. Not all of these needs to happen though.
The most prominent is floodgate, blocks and json serialization

* try patching BigInt so we don't have to check every property if it's bigint [here](https://github.com/tallycash/extension/blob/831676b8807e61b59a99821f0cc2ba80992b8f3f/background/lib/utils/index.ts#L77)  but use only a simple `JSON.stringify()` (ugly hack, only worth it if the performance gain is significant)
* prune unused data from redux and/or implement paging [flowdock thread](https://www.flowdock.com/app/cardforcoin/tech/threads/mBOx5TsYPZ6JNqtUg0dJ42cRiJg) (activities, logs, transaction inputs)
* try to mitigate "blocks" event emits firing rapidly in a short period of time 
* finish #1296 to make persisting state reasonable
* check if there is a better way to generate the cachekey for `memoizedMergeAssets`
* rewrite store persistance so it's not persisting data redundantly but grabs what it can from services on startup and only persist the rest
* clean up from previous installs 
* stop redux store from getting bigger with time

**Comment by greg-nagy** [comment]
Closed in favor of #2269 2269
