### ISSUE TITLE
Gas fee: Upgrade

### ISSUE THREAD

**Issue by greg-nagy** [tallycash/extension#1359]
# Acceptance criteria
[Economic Completeness](https://coda.io/d/Minimum-Viable-Launch_dznBnP8Wtkc/Economic-Completeness_suVk6#_luGFS) ⚠️ WIP as of 5/4. Make sure to check it when finalized!
- [x] Design update is implemented
- [ ] User is blocked from attempting a transaction if they don’t have enough ETH
- [x] We’ve performed a quick spot check to confirm if gas estimates and fees for ETH/ERC20 sends, approvals, etc. are on par with MM 

# Design
Gas Control [Figma link](https://www.figma.com/file/q8gfu9XTbYBF07KMnDCtsD/?node-id=1470%3A54326)
Design ticket https://github.com/tallycash/product-design/issues/13

# Discovery / Research / Spike
- [ ] Might require some documentation on [Blocknative estimations](https://www.blocknative.com/blog/base-fee-prediction-and-intelligent-max-fee)
- [x] Henry's concerns:
  - [x] Value items and their meanings: miners === max priority fee, max base vs base fee? 
  - [x] How does our design relates to the API spec and the eip
    https://www.blocknative.com/blog/eip-1559-fees
    https://eips.ethereum.org/EIPS/eip-1559
  > Max Priority Fee = Miner
Max Base = Max Fee - Miner
Even though max base isn't something Blocknative and EIP-1559 outright specifies, it's a sensible repackaging to make the interface easier to understand

# Work breakdown
- [x] #1413
- [x] Gas limit should have a predefined value https://github.com/tallycash/extension/issues/1367
- [x] Gas limit increments should change by 1000, not 1 https://github.com/tallycash/extension/issues/1369

### Draft or open PRs
- Gas Limit error when is set too low https://github.com/tallycash/extension/issues/1368
-  UI work: #1302 
https://github.com/tallycash/extension/pull/1522
https://github.com/tallycash/extension/pull/1523
- #1623

### Next
- [ ] User is blocked from attempting a transaction if they don’t have enough ETH

### Not planned yet
- [ ] Slippage tolerance for swap (In gas control slide-up) https://github.com/tallycash/extension/issues/1169

# Bugs
- [x] #1643
- [x] #1644
- [x] #1645
- [x] #1648
- [x] #1649
