### ISSUE TITLE
Polygon

### ISSUE THREAD

**Issue by 0xDaedalus** [tallycash/extension#1534]
# Acceptance criteria
- [ ] TBD Based on Design

# Dependencies
- [ ] Final Design of what L2 Support will look like.

# Work Breakdown

## Extension Features
- [x] https://github.com/tallycash/extension/issues/1532
- [x] https://github.com/tallycash/extension/issues/1529
- [x] https://github.com/tallycash/extension/issues/1508
- [ ] https://github.com/tallycash/extension/issues/1506
- [x] https://github.com/tallycash/extension/issues/1504
- [x] https://github.com/tallycash/extension/issues/1503
- [x] https://github.com/tallycash/extension/issues/1502
- [x] https://github.com/tallycash/extension/issues/1501
- [x] https://github.com/tallycash/extension/issues/1487
- [x] https://github.com/tallycash/extension/issues/1482
- [x] https://github.com/tallycash/extension/issues/1581
- [x] https://github.com/tallycash/extension/issues/1584

## Integrations
- [x] https://github.com/tallycash/extension/issues/1481
- [ ] https://github.com/tallycash/extension/issues/1546
- [x] https://github.com/tallycash/extension/issues/1547

## Bugs
- [x] https://github.com/tallycash/extension/issues/1583
- [x] https://github.com/tallycash/extension/issues/1582
- [x] #1652
  - If I am on mainnet and my matic account is 0 on mainnet, it shouldn't show up as an asset
- [x] #1614
