### ISSUE TITLE
Key API

### ISSUE THREAD

**Issue by mhluongo** [tallycash/extension#158]
Expose an interface via Redux to...

- [x] import existing MetaMask 12-word seed phrases (#237)
- [x] generate new 24-word mnemonics (#237)
- [x] #763
- [x] unlock / load persisted keyrings (#237)
- [x] #513
- [x] #762
- [x] sign a tx from a chosen address (#269)

Relies on #155
