### ISSUE TITLE
NFT view support

### ISSUE THREAD

**Issue by henryboldi** [tallycash/extension#1690]
- [x] #1845
- [x] #1691

<hr/>

<img width="803" alt="NFT list" src="https://user-images.githubusercontent.com/1918798/176715808-039455c4-23b0-4391-af1d-edaf5d004694.png">

- [x] #1692

<hr/>

<img width="467" alt="Single NFT" src="https://user-images.githubusercontent.com/1918798/176715661-9b946fd7-22f7-40b7-9027-e1ad4df5d2fc.png">

- [x] #1693
    

- Image (displayed square)
-   Title (truncate if needed)
-   Token id (do NOT truncate)
-     Associated with contract 
-   onClick 
-     ~~Open shared slide up menu~~
-     Display in original aspect ratio
-     External link button that opens NFT in another tab
-       !! TBD what URL this will go to
-   Hover
-     Overlay white 20%
<hr/>
 
 
<img width="360" alt="Notification" src="https://user-images.githubusercontent.com/1918798/176715477-6ea71655-4b57-45ed-ab5b-76884796fd97.png">

 
- [x] #1694

- Can be dismissed
- On both pages

<hr/>
<img width="330" alt="first time" src="https://user-images.githubusercontent.com/1918798/176715317-c07f544d-0067-4dfe-b8f9-ac0ada72fb6a.png">

- [x] #1695

<hr/>

- [x] #1696
- [x] #1856
- [x] #1857
- [x] https://github.com/tallycash/extension/issues/1868
- [ ] https://github.com/tallycash/extension/issues/1867
- [x] https://github.com/tallycash/extension/issues/1862
<hr/>
