### ISSUE TITLE
Name / content resolution service

### ISSUE THREAD

**Issue by mhluongo** [tallycash/extension#225]
We need to be able to resolve...

- [ ] IPFS content
- [x] ENS names to
  - [x] #411
  - [x] Addresses on other networks
  - [ ] #412 
  - [x] #413
- [x] #414
- [x] Unstoppable Domain names to
  - [x] Addresses on Ethereum
  - [x] Addresses on other networks
  - [ ] Websites / dApps
- [ ] Handshake/HNS names to websites

... in rough priority order
