### ISSUE TITLE
CPU issues next round

### ISSUE THREAD

**Issue by greg0x** [tallycash/extension#2269]
the issue on Chrome v0.16.1 from @Naxsun 

# Problems
- redux store is huge 
  - case 1 (Naxsun): account.accountsData 25%, activities 60%
    - persisting redux cache takes a lot of resources (40% of cpu usage)
    - dexie iterate is (19% cpu) // at least I _think_ this is because of it 
  - case 2 (hyphenized): assets slice is huge 93% of the redux store (using the `test test .... junk` seed)
- IndexedDB becomes slow when it's flooded (we had issues from this before, don't have measurements now)
- garbacollector runs a lot (19% of cpu) - this is probably because we use destructoring a lot 
- `assets` and `accountsWithBalances` events are coming in bursts

# Recomended solution
- mitigate huge redux store size problem
  - [x]  #1885 
  - [x] find a better way to represent assets in the asset slice
  - [ ] find a better way to represent account.accountsData.balances (16 token balance takes up ~97% of the slice)
- ease up on expensive codepaths
  - redux-cache
    - [x] #2285 
    - [ ] debounce redux changes #1296 
    - [ ] remove slices from persistence which are initialized on startup
      - refactor as many services as possible to initialise redux on startup
   - [ ] refactor indexedDB writes to be done in batches / don't persist anything in a loop into indexedDB
- [ ] batch `assets` and `accountsWithBalances` event emmits
- [ ] try patching BigInt so we don't have to check every property if it's bigint [here](https://github.com/tallycash/extension/blob/831676b8807e61b59a99821f0cc2ba80992b8f3f/background/lib/utils/index.ts#L77)  but use only a simple `JSON.stringify()` (ugly hack, only worth it if the performance gain is significant)

[CPU-20220921T161607.cpuprofile.zip](https://github.com/tallycash/extension/files/9618039/CPU-20220921T161607.cpuprofile.zip)

[redux size Naxsun.txt](https://github.com/tallycash/extension/files/9618036/redux.size.Naxsun.txt)

[Case2 redux size: definitelynotajson.zip](https://github.com/tallycash/extension/files/9633529/definitelynotajson.zip)
