### ISSUE TITLE
NFTs update

### ISSUE THREAD

**Issue by jagodarybacka** [tallycash/extension#2594]
This is a tracking issue for all the work we need to do for NFTs page update

### UI tasks

- [ ] Add NFTs page to the wallet
- [ ] Create NFTs page header
- [ ] Add NFTs and Badges tabs
- [ ] Create NFT collection component
- [ ] Handle expanding NFT collection component
- [ ] Create a single NFT preview
- [ ] Create NFTs filters selector

### Background tasks

**TODO**

**Comment by greg-nagy** [comment]
Discussion points
- Do you plan to use the existing setup — eg indexing service or come up with a different structure for the NFTs (an nft can be thought of as a coin that you can only have 1 of)
- What data do you need?
- What data sources do you have? Is one source for each kind of data enough?
- How can you make sure the performance is good? Quick enough, smooth enough
    - fetching the images
    - making sure the UI is performant even with large number of NFTs  — Vlad wants infinite scroll
    - What, when and how will trigger data fetching / cache revalidation?
- What are the constraints of delivering this feature?
    - Can you do it alone? Do you want to? If not who do you need help from and in what?
- Costs model and pricing?

**Comment by jagodarybacka** [comment]
> Do you plan to use the existing setup

Not really as we can assume all users care about the tokens but not all of them use NFTs. Let's update NFTs data on account load and on entering pages where NFTs lists are visible.

> What data do you need

Details of NFT and its collection, pricing.

> What data sources do you have

Let's use NFTs data provider that is able to give us all the data we need right now (SH + POAP)

> How can you make sure the performance is good

Treat redux store as a cache for data that should be available instantly. Use DB as a data provider for frontend that will be updating redux cache as needed. Update NFTs data when user enter the place in the app that is displaying NFTs.

> Can you do it alone

All frontend-only tasks are good to be done in parallel with background work. Collection component and single NFTs components are blocked by the background.

> Costs model

For now we will use providers we are already using. To be discovered if we will need higher tier plan.

**Comment by greg-nagy** [comment]
I just want to leave a note here that writing tests were not included in the original plan — mainly because we were focusing on getting something out. 

It seems that we won't release this feature this year so I think it's reasonable to add tests as work items for the work. 
I am happy to jump in and help writing tests because this feature is huge!
