### ISSUE TITLE
dApp Connections v1

### ISSUE THREAD

**Issue by Shadowfiend** [tallycash/extension#366]
This is a tracking issue for enabling dApp connections in the extension. 
Its implementation should be largely based on the [dApp Connections RFC](https://coda.io/d/Minimum-Viable-Launch_dznBnP8Wtkc/RFC-dApp-Connections_suxkn#_lueqf).

# v1.0

## 01.17 - 01.23 > 01.24 - 01.30
- [x] #842
- [x] #833 
- [x] #849

## Backlog
- [x] #486
- [x] Implement `wallet_watchAsset` RPC method (saddle integration update is required)
- [x] #504
- [x] `window.ethereum` protection: not writable, not deletable, object methods also protected 
- ~~Tally provider in ethers.js [based on the MM provider](https://github.com/ethers-io/ethers.js/blob/master/packages/experimental/src.ts/metamask-provider.ts)~~
- [x] web3modal integration PR
- [ ] Rate limit in `ProviderBridgeService` for better security
- [ ] `TallyWindowProvider` refactor: single event listener refactor (arrow function)
  - [x] arrow: https://github.com/tallycash/tally-extension/pull/440#discussion_r753485052
  - [x] single listener: https://github.com/tallycash/tally-extension/pull/440#discussion_r753509947
  - [ ] Map typing (or simple object)
- [x] `TallyWindowProvider` refactor:  custom handlers by payload 
  - https://github.com/tallycash/tally-extension/pull/440#discussion_r753504700
- [x] #466
- [ ]  threshold integration PR https://github.com/threshold-network/token-dashboard
- [ ] Handle not standardised RPC methods in `InternalEthereumProviderService` for compatibility
- [x] Move dApp connection responsibility from `CorePage` > `TopMenuConnectedDAppInfo`
  - https://github.com/tallycash/extension/pull/570#discussion_r767186696
  - https://github.com/tallycash/extension/pull/570#discussion_r767193266
- [ ] `PermissionRequest` type revise 
  - `faviconUrl` -> `faviconURL`
  - separate `PermissionRequest` from `PermissionResponse` 
     this implicitly implies that the current address is populated when the UI is shown and not in `main.ts`
- [ ] `provider-bridge-shared` typing simplification https://github.com/tallycash/extension/pull/687#discussion_r770738041
- [ ] combine the preference setting asyncThunks in ui slice into  `setPreference` async thunk that handles all type of preference change. Should work for single change and muiltiple
- [ ] Rename `defaultWallet` to `isDefaultWallet` https://github.com/tallycash/extension/pull/731#discussion_r772648537
- [x] Make sure that the internal dApps gets all the accounts with `eth_accounts` https://github.com/tallycash/extension/pull/731#discussion_r772641094
- [ ] use `accounts` terminology in `provider-bridge` and permission handling 
- [x] Always return all the connected accounts for `eth_accounts` and `eth_requestAccounts` with the current account being the first element https://github.com/tallycash/extension/pull/731#discussion_r772663380
- [x] default wallet overwrite protection
- [ ] set default wallet on only if there is an account (imported or readonly)
- [ ] update onboardjs integration to use `window.tally` directly

# Archive 
## Tracking issues
- #417
- #387
- #388
- #389
- #391
- #390
- #461

## Community Edition 

- [x] Proper connection handling in `ProviderBridgeService`
- [x] Implement deprecated methods in `TallyWindowProvider` for compatibility 
(send, sendAsync, close, networkChanged, notification)
- [x] `TallyWindowProvider` refactor:  `if (typeof result === "number" && this.chainId != result)`
- [x] `TallyWindowProvider` refactor:  move the transport specific checks and unwrapping logic to the transport object (and have a proper implementation for the transport object creation)
- [x] #417
- [x] `TallyWindowProvider` initial setup (demos are working) 
  - #393 
  - #439 
- [x] `ProviderBridge` (content script) initial setup (demos are working) 
  - #393 
  - #439 
- [x] #462
  - #451 
- [x] #463
  - #451 
 ### 29th November - 5th December
- [x] #464
- [x] #465
- [x] #467
- [x] #479
- [x] #473
- [x] #485
### 6-12 December 
- [x] #478 
- [x] #476
- [x] #470
- [x] #482
- [x] #480 (Henry)
- [x] #481
- [x] dApp requested transaction signing
- [x] #483
- [x] #484
- [x] #487
- [x] #489
- [x] #488
