### ISSUE TITLE
Sending ERC-20

### ISSUE THREAD

**Issue by wojciech-turek** [tallycash/extension#879]
This is the tracking issue, for sending ERC-20 tokens.

## Design
Send Page [Figma link](https://www.figma.com/file/q8gfu9XTbYBF07KMnDCtsD/UI---Dark?node-id=4082%3A123725)

# Discovery / Research / Spike
- [ ] What type of a call we need to make to the keyring service to send a transaction
- [ ] What needs to be in the input data and how do we create it
- [ ] Do we already have functions that we can use for this feature

### 01.24 - 01.25

- [ ] #881
- [ ] #882
- [ ] Manually test sending and receiving tokens

### Backlog

- [ ] Allow users to search for tokens by contract address and if found ask to add to the wallet

Related tickets:
- [ ] #84 
- [ ] #261 (duplicate of 84 but with more details)
