### ISSUE TITLE
Earn (some moolah)

### ISSUE THREAD

**Issue by wojciech-turek** [tallycash/extension#886]
This is the tracking issue for Earn functionality.

# Design
Earn page [Figma link](https://www.figma.com/file/q8gfu9XTbYBF07KMnDCtsD/UI---Dark?node-id=6062%3A146317)

# Feature pitch

https://coda.io/d/Minimum-Viable-Launch_dznBnP8Wtkc/Earn_sujPB#_luzpf

# UI flow 

https://www.figma.com/file/xO23u7tEDMRoNTQQlROXDP/Earn-with-Wo?node-id=0%3A1

# Discovery / Research / Spike
- [x] Get the ABI for Earn contracts
- [x] What data needs to be sent to the contract and its formatting + what do we return and display in the UI
- [x] Do we use the sign transaction page when user want to deposit funds in the earn contract
- [ ] How do we await a transaction mint in the UI - needed for ApprovalTarget initial approve call
- [ ] Displaying APR - Need to talk to Keep folds
- [ ] Displaying total claimable rewards
- [ ] Displaying TVL - Need to talk to Keep folds
- [ ] What placeholder do we use when TVL and other data are loading?  Need design (@VladUXUI)
- [ ] Could we deploy a mock contract to test APR and TVL data fetching?
- [ ] What if someone wants to withdraw only 50% of their total deposited amount, can we support it?

### 31.01 - 02.04

- [X] Have a call with Vlad about Earn page design
- [x] https://github.com/tallycash/extension/pull/927
- [x] #930
- [x] Review progress with @greg-nagy 

### 02.07 - 02.11

- [x] Earn background flow, create proper typings and apply suggestions from last week
- [ ] Display APR
- [ ] Display TVL
- [ ] Display Claimable Rewards
- [ ] Deposit, getRewards and Withdraw functionality
- [ ] Test earn background and UI data flow with mock data
- [ ] Plug in the contracts (?) and test

### Side-quests

- [X] Creating re-usable max balance selection to shared asset input

### Backlog

TBD

Related tickets:
- [x] #377

**Comment by jagodarybacka** [comment]
Closing as this is outdated
